# Grundlagen von Numpy

## ndarray: Mehrdimensionales Array-Objekt

### Erzeugen

In [2]:
import numpy as np
data1 = [6,7,8,0,1]

In [6]:
arr1 = np.array(data1)
arr1

array([6, 7, 8, 0, 1])

In [12]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2
arr2.ndim # Dimensionen
arr2.shape # 

(2, 4)

Zusätzlich zu np.array gibt es noch andere Funktionen, mit denen man Arrays erzeugen kann:

In [15]:
np.zeros(10)
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

## Datentypen für ndarrays

In [18]:
arr1 = np.array(data1, dtype=np.float64)
arr1
arr2 = np.array(data2, dtype=np.int32)
arr2
arr2.dtype

dtype('int32')

## Operationen zwischen Arrays und Skalaren

Arrays erlauben operationen *ohne* Schleifen durchzuführen (Vektorisierung).

In [24]:
arr3 = np.array([[1.,2.,3.],[4.,5.,6.]])
arr3
arr3 * arr3
arr3 - arr3
1/arr3
arr3 ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

## Einfaches Indizieren und Slicing
Eindimensionale Arrays sind einfach:

In [27]:
arr4 = np.arange(10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr4[5] # das fünfte Element
arr4[5:8] # slice operator

array([5, 6, 7])

In [ ]:
Slices sind Teiloperationen (Views) und jede Änderung an der View schlägt sich auf das Array nieder:

In [33]:
arr4[5:8] = 12
arr4
arr_slice = arr4[5:8]
arr_slice
arr_slice[1] = 1234
arr4

array([   0,    1,    2,    3,    4,   12, 1234,   12,    8,    9])

### Höherdimensionale Arrays

In [4]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr2d[0][2]
arr2d[0,2] # rekursiv

3

![title](img/elemente_in_einem_NumPy_array_indizieren.png)

In [52]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [53]:
arr3d[0] # ist ein 2x3 Array

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [56]:
arr3d[1,0]

array([7, 8, 9])

### Indizieren mit Slices

In [57]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
arr2d[:2,1]

array([2, 5])

![title](img/mehrdimensionales_array_ausschneiden.png)

## Übungen

### Übung 1
Bilde folgende Tabelle als Array ab:

| | | | |
|-|-|-|-|
| 1 | 11 | 89  | 10 | 
| 1 | 12 | 144 | 23 |
| 2 | 13 | 233 | 2  |
| 4 | 14 | 377 | 44 |

## Übung 2
Aus dem dem Array der Übung 1 soll ein 2 x 2 Array ausgeschnitten werden, der sich in der Mitte der Tabelle befindet (12,144,13,233). 